// USERS LIST

export const SET_ALL_USERS = "SET_ALL_USERS";
export const SET_DIALOG_USERS = "SET_DIALOG_USERS";
export const SET_USER = "SET_USER";
export const FETCHING_IS_USERS = "IS_FETCHING_USERS";
export const FETCHING_DIALOG_IS_USERS = "FETCHING_DIALOG_IS_USERS";

// HELPERS

export const IS_FETCHING = "IS_FETCHING";

// CURRENT USER
export const REGISTER_USER = "REGISTER_USER";
export const SET_SESSION = "SET_SESSION";
export const SET_USER_INFO = "SET_USER_INFO";
export const UPDATE_USER_AVATAR = "UPDATE_USER_AVATAR";

// DIALOG
export const DIALOG_GET = "DIALOGS_GET";
export const DIALOG_ADD_MESSAGE = "DIALOG_ADD_MESSAGE";
export const DIALOG_IS_FETCHING = "DIALOG_IS_FETCHING";
