// USERS LIST

export const SET_USERS = "SET_USERS";
export const SET_USER = "SET_USER";

// HELPERS

export const IS_FETCHING = "IS_FETCHING";

// CURRENT USER
export const REGISTER_USER = "REGISTER_USER";
export const SET_SESSION = "SET_SESSION";
export const SET_USER_INFO = "SET_USER_INFO";
export const UPDATE_USER_AVATAR = "UPDATE_USER_AVATAR";

// DIALOG
export const DIALOG_GET = "DIALOGS_GET";
export const DIALOG_ADD_MESSAGE = "DIALOG_ADD_MESSAGE";
